server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: mdm-adapter
  datasource:
    url: jdbc:postgresql://localhost:5433/mdm-adapter
    username: postgres
    password: postgres
    hikari:
      schema: mdm
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema}
  liquibase:
    change-log: db/changelog/changelog-master.yaml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  kafka:
    bootstrap-servers: 81.30.105.54:29092
    producer:
      acks: all
    consumer:
      group-id: mdm-group
  cloud:
    openfeign:
      client:
        config:
          user-data-service-one-client:
            read-timeout: 3000
            connect-timeout: 3000
          user-data-service-two-client:
            read-timeout: 3000
            connect-timeout: 3000

mdm:
  system:
    username: chugunovao
  kafka:
    mdm-event:
      enabled: true
      change-phone:
        topic-in: MDM.Change.Phone.IN.V1
  service:
    user-data-one:
      url: http://81.30.105.54:8080
      response-timeout-seconds: 5
    user-data-two:
      url: http://81.30.105.54:8080
      response-timeout-seconds: 5


